export type Specs = {
  processor: string;
  ram: string;
  storage: string;
  gpu: string;
  screenSize: string;
  resolution: string;
  refreshRate: string;
  operatingSystem: string;
  battery: string;
  weight?: string;
  warranty: string;
  usage: "Gaming" | "Coding" | "Creator" | "Business" | "Student" | "Premium";
  screen?: string;
};

export type Product = {
  id: string;
  name: string;
  brand: "ASUS" | "Lenovo" | "Acer" | "HP" | "Dell" | "MSI" | "Apple" | string;
  category: string;
  price: number;
  oldPrice?: number;
  rating: number;
  reviews: number;
  stock: number;
  badges: string[];
  image: string;
  gallery?: string[];
  warranty: string;
  description: string;
  specs: Specs;
  sold: number;
  active: boolean;
  createdAt: string;
};

export type Category = { id: string; name: string; slug: string; icon: string; count: number };
export type Brand = { id: string; name: string; country: string; products: number };

export type OrderStatus = "Pending" | "Processing" | "Shipped" | "Completed" | "Cancelled";

export type Order = {
  id: string;
  customer: string;
  email: string;
  date: string;
  total: number;
  status: OrderStatus;
  payment: string;
  items: { name: string; qty: number; price: number }[];
};

export const formatIDR = (n: number) =>
  "Rp" + new Intl.NumberFormat("id-ID", { maximumFractionDigits: 0 }).format(n);

export const categories: Category[] = [
  { id: "c1", name: "Gaming Laptop", slug: "gaming-laptop", icon: "Gamepad2", count: 17 },
  { id: "c2", name: "Coding & Programming", slug: "coding-programming", icon: "Code", count: 20 },
  { id: "c3", name: "Creator & Design", slug: "creator-design", icon: "Palette", count: 13 },
  { id: "c4", name: "Business Laptop", slug: "business-laptop", icon: "Briefcase", count: 10 },
  { id: "c5", name: "Student Laptop", slug: "student-laptop", icon: "GraduationCap", count: 10 },
];

export const brands: Brand[] = [
  { id: "b1", name: "ASUS", country: "Taiwan", products: 10 },
  { id: "b2", name: "Lenovo", country: "China", products: 10 },
  { id: "b3", name: "Acer", country: "Taiwan", products: 10 },
  { id: "b4", name: "HP", country: "USA", products: 10 },
  { id: "b5", name: "Dell", country: "USA", products: 10 },
  { id: "b6", name: "MSI", country: "Taiwan", products: 10 },
  { id: "b7", name: "Apple", country: "USA", products: 10 },
];

const LAPTOP_IMG = "/images/laptop.jpg";

export const seedProducts: Product[] = [
  {
    id: "asus-01",
    name: "ASUS Vivobook Go 14 E1404FA",
    brand: "ASUS",
    category: "Student Laptop",
    price: 5499000,
    oldPrice: 5999000,
    rating: 4.6,
    reviews: 128,
    stock: 14,
    badges: ["Best Value", "Student Pick"],
    image: "/images/products/asus-01/1.jpg",
    gallery: ["/images/products/asus-01/1.jpg", "/images/products/asus-01/2.jpg", "/images/products/asus-01/3.jpg", "/images/products/asus-01/4.jpg"],
    warranty: "2 years official ASUS warranty",
    description: "Compact and lightweight 14-inch laptop powered by AMD Ryzen 3 7320U, perfect for daily study, office tasks, and online meetings with 180-degree lay-flat hinge.",
    specs: {
      processor: "AMD Ryzen 3 7320U",
      ram: "8GB LPDDR5",
      storage: "256GB NVMe SSD",
      gpu: "AMD Radeon 610M",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "42Wh \u2014 up to 7 hours",
      weight: "1.38 kg",
      warranty: "2 years official ASUS warranty",
      usage: "Student",
      screen: "14.0\" FHD Anti-Glare",
    },
    sold: 215,
    active: true,
    createdAt: "2026-08-01",
  },
  {
    id: "asus-02",
    name: "ASUS Vivobook 14 A1405VA",
    brand: "ASUS",
    category: "Coding & Programming",
    price: 8299000,
    oldPrice: 8999000,
    rating: 4.7,
    reviews: 94,
    stock: 11,
    badges: ["Top Seller"],
    image: "/images/products/asus-02/1.jpg",
    gallery: ["/images/products/asus-02/1.jpg", "/images/products/asus-02/2.jpg", "/images/products/asus-02/3.png", "/images/products/asus-02/4.jpg"],
    warranty: "2 years official ASUS warranty",
    description: "Reliable 14-inch productivity workhorse with 13th Gen Intel Core i5 and 16:10 WUXGA display for enhanced vertical coding workspace.",
    specs: {
      processor: "Intel Core i5-1335U",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "WUXGA (1920 x 1200)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "42Wh \u2014 up to 8 hours",
      weight: "1.60 kg",
      warranty: "2 years official ASUS warranty",
      usage: "Coding",
      screen: "14.0\" WUXGA 16:10 IPS-Level",
    },
    sold: 182,
    active: true,
    createdAt: "2026-08-02",
  },
  {
    id: "asus-03",
    name: "ASUS Vivobook 14 OLED M1405YA",
    brand: "ASUS",
    category: "Creator & Design",
    price: 10499000,
    oldPrice: 11299000,
    rating: 4.8,
    reviews: 110,
    stock: 9,
    badges: ["2.8K OLED", "Vivid Colors"],
    image: "/images/products/asus-03/1.jpg",
    gallery: ["/images/products/asus-03/1.jpg", "/images/products/asus-03/2.jpg", "/images/products/asus-03/3.jpg", "/images/products/asus-03/4.png"],
    warranty: "2 years official ASUS warranty",
    description: "Stunning 2.8K 90Hz OLED display with 100% DCI-P3 color gamut, powered by 8-core AMD Ryzen 7 7730U for creative editing and multitasking.",
    specs: {
      processor: "AMD Ryzen 7 7730U",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "AMD Radeon Graphics",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "90Hz",
      operatingSystem: "Windows 11 Home",
      battery: "50Wh \u2014 up to 9 hours",
      weight: "1.40 kg",
      warranty: "2 years official ASUS warranty",
      usage: "Creator",
      screen: "14.0\" 2.8K OLED 90Hz 0.2ms 600nits HDR",
    },
    sold: 140,
    active: true,
    createdAt: "2026-08-03",
  },
  {
    id: "asus-04",
    name: "ASUS Vivobook S 14 OLED S5406SA",
    brand: "ASUS",
    category: "Creator & Design",
    price: 15999000,
    oldPrice: 16999000,
    rating: 4.9,
    reviews: 88,
    stock: 8,
    badges: ["Intel Evo", "3K 120Hz OLED"],
    image: "/images/products/asus-04/1.jpg",
    gallery: ["/images/products/asus-04/1.jpg", "/images/products/asus-04/2.jpg", "/images/products/asus-04/3.png", "/images/products/asus-04/4.jpg"],
    warranty: "2 years official ASUS VIP warranty",
    description: "Ultra-sleek Intel Core Ultra 7 AI-powered laptop with dedicated NPU, 3K 120Hz Lumina OLED display, RGB backlit keyboard, and all-metal chassis.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "16GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "14.0\"",
      resolution: "3K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "75Wh \u2014 up to 14 hours",
      weight: "1.30 kg",
      warranty: "2 years official ASUS VIP warranty",
      usage: "Creator",
      screen: "14.0\" 3K OLED 120Hz 0.2ms 100% DCI-P3",
    },
    sold: 95,
    active: true,
    createdAt: "2026-08-04",
  },
  {
    id: "asus-05",
    name: "ASUS Zenbook 14 OLED UX3405MA",
    brand: "ASUS",
    category: "Business Laptop",
    price: 18999000,
    oldPrice: 19999000,
    rating: 4.9,
    reviews: 115,
    stock: 7,
    badges: ["Premium Ultrabook", "Intel Ultra 7"],
    image: "/images/products/asus-05/1.jpg",
    gallery: ["/images/products/asus-05/1.jpg", "/images/products/asus-05/2.jpg", "/images/products/asus-05/3.png", "/images/products/asus-05/4.jpg"],
    warranty: "2 years official ASUS VIP warranty",
    description: "Flagship lightweight premium laptop with CNC all-metal build, 32GB RAM, 75Wh battery, and crystal-clear Harman Kardon audio.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "32GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "75Wh \u2014 up to 15 hours",
      weight: "1.20 kg",
      warranty: "2 years official ASUS VIP warranty",
      usage: "Business",
      screen: "14.0\" 2.8K OLED 120Hz 0.2ms",
    },
    sold: 82,
    active: true,
    createdAt: "2026-08-05",
  },
  {
    id: "asus-06",
    name: "ASUS Zenbook S 16 OLED UM5606WA",
    brand: "ASUS",
    category: "Creator & Design",
    price: 23499000,
    oldPrice: 24999000,
    rating: 4.9,
    reviews: 76,
    stock: 6,
    badges: ["Ceraluminum", "Copilot+ PC"],
    image: "/images/products/asus-06/1.jpg",
    gallery: ["/images/products/asus-06/1.jpg", "/images/products/asus-06/2.jpg", "/images/products/asus-06/3.jpg", "/images/products/asus-06/4.jpg"],
    warranty: "2 years official ASUS VIP warranty",
    description: "Next-gen Copilot+ PC crafted with revolutionary high-tech Ceraluminum, powered by AMD Ryzen AI 9 365 with 50 TOPS NPU and 3K 120Hz OLED screen.",
    specs: {
      processor: "AMD Ryzen AI 9 365",
      ram: "24GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "AMD Radeon 880M",
      screenSize: "16.0\"",
      resolution: "3K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "78Wh \u2014 up to 16 hours",
      weight: "1.50 kg",
      warranty: "2 years official ASUS VIP warranty",
      usage: "Creator",
      screen: "16.0\" 3K OLED 120Hz 500nits HDR",
    },
    sold: 64,
    active: true,
    createdAt: "2026-08-06",
  },
  {
    id: "asus-07",
    name: "ASUS ExpertBook B5 B5402CBA",
    brand: "ASUS",
    category: "Business Laptop",
    price: 14299000,
    oldPrice: 15499000,
    rating: 4.8,
    reviews: 60,
    stock: 10,
    badges: ["Enterprise Grade", "Windows 11 Pro"],
    image: "/images/products/asus-07/1.png",
    gallery: ["/images/products/asus-07/1.png", "/images/products/asus-07/2.jpg", "/images/products/asus-07/3.jpg", "/images/products/asus-07/4.jpg"],
    warranty: "3 years official ASUS Onsite warranty",
    description: "Enterprise-grade commercial laptop with dual SSD support, TPM 2.0 security, physical webcam shield, and military-grade durability.",
    specs: {
      processor: "Intel Core i7-1355U",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "63Wh \u2014 up to 11 hours",
      weight: "1.25 kg",
      warranty: "3 years official ASUS Onsite warranty",
      usage: "Business",
      screen: "14.0\" FHD Anti-Glare 400nits",
    },
    sold: 73,
    active: true,
    createdAt: "2026-08-07",
  },
  {
    id: "asus-08",
    name: "ASUS TUF Gaming A15 FA506NC",
    brand: "ASUS",
    category: "Gaming Laptop",
    price: 11799000,
    oldPrice: 12499000,
    rating: 4.8,
    reviews: 165,
    stock: 12,
    badges: ["Best Seller", "TUF Military Grade"],
    image: "/images/products/asus-08/1.jpg",
    gallery: ["/images/products/asus-08/1.jpg", "/images/products/asus-08/2.jpg", "/images/products/asus-08/3.jpg", "/images/products/asus-08/4.jpg"],
    warranty: "2 years official ASUS warranty",
    description: "High-durability gaming laptop with AMD Ryzen 5, RTX 3050, 144Hz Adaptive-Sync display, and comprehensive cooling system.",
    specs: {
      processor: "AMD Ryzen 5 7535HS",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 3050 4GB",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "144Hz",
      operatingSystem: "Windows 11 Home",
      battery: "48Wh \u2014 up to 6 hours",
      weight: "2.30 kg",
      warranty: "2 years official ASUS warranty",
      usage: "Gaming",
      screen: "15.6\" FHD 144Hz IPS-level",
    },
    sold: 290,
    active: true,
    createdAt: "2026-08-08",
  },
  {
    id: "asus-09",
    name: "ASUS TUF Gaming F15 FX507VV",
    brand: "ASUS",
    category: "Gaming Laptop",
    price: 17299000,
    oldPrice: 18499000,
    rating: 4.9,
    reviews: 130,
    stock: 8,
    badges: ["RTX 4060", "High Performance"],
    image: "/images/products/asus-09/1.jpg",
    gallery: ["/images/products/asus-09/1.jpg", "/images/products/asus-09/2.jpg", "/images/products/asus-09/3.jpg", "/images/products/asus-09/4.jpg"],
    warranty: "2 years official ASUS warranty",
    description: "Serious gaming and content creation powerhouse featuring 13th Gen Intel Core i7, 140W RTX 4060 GPU with MUX Switch + NVIDIA Advanced Optimus.",
    specs: {
      processor: "Intel Core i7-13620H",
      ram: "16GB DDR5",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "144Hz",
      operatingSystem: "Windows 11 Home",
      battery: "90Wh \u2014 up to 8 hours",
      weight: "2.20 kg",
      warranty: "2 years official ASUS warranty",
      usage: "Gaming",
      screen: "15.6\" FHD 144Hz 100% sRGB",
    },
    sold: 175,
    active: true,
    createdAt: "2026-08-09",
  },
  {
    id: "asus-10",
    name: "ASUS ROG Zephyrus G16 GU605MI",
    brand: "ASUS",
    category: "Gaming Laptop",
    price: 31999000,
    oldPrice: 33999000,
    rating: 4.9,
    reviews: 92,
    stock: 5,
    badges: ["ROG Flagship", "OLED 240Hz"],
    image: "/images/products/asus-10/1.jpg",
    gallery: ["/images/products/asus-10/1.jpg", "/images/products/asus-10/2.jpg", "/images/products/asus-10/3.jpg", "/images/products/asus-10/4.jpg"],
    warranty: "2 years official ASUS VIP warranty",
    description: "Ultra-slim CNC aluminum gaming masterpiece with ROG Nebula OLED 240Hz display, Intel Core Ultra 9, and RTX 4070 graphics.",
    specs: {
      processor: "Intel Core Ultra 9 185H",
      ram: "32GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4070 8GB",
      screenSize: "16.0\"",
      resolution: "2.5K (2560 x 1600)",
      refreshRate: "240Hz",
      operatingSystem: "Windows 11 Home",
      battery: "90Wh \u2014 up to 9 hours",
      weight: "1.85 kg",
      warranty: "2 years official ASUS VIP warranty",
      usage: "Gaming",
      screen: "16.0\" 2.5K OLED 240Hz 0.2ms G-Sync",
    },
    sold: 89,
    active: true,
    createdAt: "2026-08-10",
  },
  {
    id: "lenovo-01",
    name: "Lenovo IdeaPad Slim 1 14AMN7",
    brand: "Lenovo",
    category: "Student Laptop",
    price: 5199000,
    oldPrice: 5699000,
    rating: 4.6,
    reviews: 140,
    stock: 15,
    badges: ["Affordable", "Student Essential"],
    image: "/images/products/lenovo-01/1.jpg",
    gallery: ["/images/products/lenovo-01/1.jpg", "/images/products/lenovo-01/2.jpg", "/images/products/lenovo-01/3.jpg", "/images/products/lenovo-01/4.jpg"],
    warranty: "2 years official Lenovo warranty",
    description: "Budget-friendly everyday laptop powered by AMD Athlon Silver, fast NVMe SSD, and Dolby Audio speakers.",
    specs: {
      processor: "AMD Athlon Silver 7120U",
      ram: "8GB LPDDR5",
      storage: "256GB NVMe SSD",
      gpu: "AMD Radeon 610M",
      screenSize: "14.0\"",
      resolution: "HD (1366 x 768)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "42Wh \u2014 up to 8 hours",
      weight: "1.38 kg",
      warranty: "2 years official Lenovo warranty",
      usage: "Student",
      screen: "14.0\" HD Anti-Glare 220nits",
    },
    sold: 240,
    active: true,
    createdAt: "2026-08-01",
  },
  {
    id: "lenovo-02",
    name: "Lenovo IdeaPad Slim 3 14IAH8",
    brand: "Lenovo",
    category: "Coding & Programming",
    price: 7999000,
    oldPrice: 8699000,
    rating: 4.7,
    reviews: 118,
    stock: 12,
    badges: ["Best Seller", "Intel H-Series"],
    image: "/images/products/lenovo-02/1.jpg",
    gallery: ["/images/products/lenovo-02/1.jpg", "/images/products/lenovo-02/2.jpg", "/images/products/lenovo-02/3.png", "/images/products/lenovo-02/4.jpg"],
    warranty: "2 years official Lenovo Premium Care",
    description: "High-efficiency laptop with powerful 45W Intel Core i5-12450H processor and FHD IPS display for smooth compilation and multitasking.",
    specs: {
      processor: "Intel Core i5-12450H",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel UHD Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "47Wh \u2014 up to 8 hours",
      weight: "1.37 kg",
      warranty: "2 years official Lenovo Premium Care",
      usage: "Coding",
      screen: "14.0\" FHD IPS 300nits Anti-Glare",
    },
    sold: 195,
    active: true,
    createdAt: "2026-08-02",
  },
  {
    id: "lenovo-03",
    name: "Lenovo IdeaPad Slim 5 14IMH9",
    brand: "Lenovo",
    category: "Coding & Programming",
    price: 11499000,
    oldPrice: 12299000,
    rating: 4.8,
    reviews: 85,
    stock: 9,
    badges: ["Intel Core Ultra", "2.8K OLED"],
    image: "/images/products/lenovo-03/1.jpg",
    gallery: ["/images/products/lenovo-03/1.jpg", "/images/products/lenovo-03/2.jpg", "/images/products/lenovo-03/3.jpg", "/images/products/lenovo-03/4.jpg"],
    warranty: "2 years official Lenovo Premium Care",
    description: "Premium aluminum slim laptop featuring Intel Core Ultra 5 with integrated AI NPU and brilliant 2.8K 120Hz OLED screen.",
    specs: {
      processor: "Intel Core Ultra 5 125H",
      ram: "16GB LPDDR5X",
      storage: "512GB NVMe SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "57Wh \u2014 up to 11 hours",
      weight: "1.46 kg",
      warranty: "2 years official Lenovo Premium Care",
      usage: "Coding",
      screen: "14.0\" 2.8K OLED 120Hz 100% DCI-P3",
    },
    sold: 112,
    active: true,
    createdAt: "2026-08-03",
  },
  {
    id: "lenovo-04",
    name: "Lenovo ThinkBook 14 G6 IRL",
    brand: "Lenovo",
    category: "Business Laptop",
    price: 13299000,
    oldPrice: 14299000,
    rating: 4.8,
    reviews: 72,
    stock: 10,
    badges: ["Business Ready", "Windows 11 Pro"],
    image: "/images/products/lenovo-04/1.jpg",
    gallery: ["/images/products/lenovo-04/1.jpg", "/images/products/lenovo-04/2.jpg", "/images/products/lenovo-04/3.jpg", "/images/products/lenovo-04/4.jpg"],
    warranty: "2 years official Lenovo Premier Support",
    description: "Robust business laptop designed for modern professionals with Intel Core i7-13700H, dual upgradable memory slots, and Windows 11 Pro.",
    specs: {
      processor: "Intel Core i7-13700H",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "WUXGA (1920 x 1200)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "60Wh \u2014 up to 10 hours",
      weight: "1.38 kg",
      warranty: "2 years official Lenovo Premier Support",
      usage: "Business",
      screen: "14.0\" WUXGA IPS 300nits Anti-Glare",
    },
    sold: 90,
    active: true,
    createdAt: "2026-08-04",
  },
  {
    id: "lenovo-05",
    name: "Lenovo ThinkPad E14 Gen 5",
    brand: "Lenovo",
    category: "Business Laptop",
    price: 12899000,
    oldPrice: 13799000,
    rating: 4.9,
    reviews: 98,
    stock: 11,
    badges: ["Legendary Keyboard", "MIL-STD-810H"],
    image: "/images/products/lenovo-05/1.jpg",
    gallery: ["/images/products/lenovo-05/1.jpg", "/images/products/lenovo-05/2.jpg", "/images/products/lenovo-05/3.jpg", "/images/products/lenovo-05/4.jpg"],
    warranty: "3 years official Lenovo Premier Support",
    description: "Iconic ThinkPad durability with TrackPoint, spill-resistant ergonomic keyboard, AMD Ryzen 7 processor, and enterprise security.",
    specs: {
      processor: "AMD Ryzen 7 7730U",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "AMD Radeon Graphics",
      screenSize: "14.0\"",
      resolution: "WUXGA (1920 x 1200)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "57Wh \u2014 up to 12 hours",
      weight: "1.41 kg",
      warranty: "3 years official Lenovo Premier Support",
      usage: "Business",
      screen: "14.0\" WUXGA IPS 300nits 100% sRGB",
    },
    sold: 134,
    active: true,
    createdAt: "2026-08-05",
  },
  {
    id: "lenovo-06",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    brand: "Lenovo",
    category: "Business Laptop",
    price: 32499000,
    oldPrice: 34999000,
    rating: 4.9,
    reviews: 64,
    stock: 5,
    badges: ["Flagship Executive", "Ultra Lightweight"],
    image: "/images/products/lenovo-06/1.jpg",
    gallery: ["/images/products/lenovo-06/1.jpg", "/images/products/lenovo-06/2.jpg"],
    warranty: "3 years official Lenovo Premier Onsite warranty",
    description: "The pinnacle of executive ultrabooks: aerospace-grade carbon fiber body weighing only 1.09kg, 2.8K 120Hz OLED, and Intel Core Ultra 7.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "32GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "57Wh \u2014 up to 15 hours",
      weight: "1.09 kg",
      warranty: "3 years official Lenovo Premier Onsite warranty",
      usage: "Business",
      screen: "14.0\" 2.8K OLED 120Hz 400nits Anti-Glare",
    },
    sold: 45,
    active: true,
    createdAt: "2026-08-06",
  },
  {
    id: "lenovo-07",
    name: "Lenovo Yoga Slim 7 Pro 14APH8",
    brand: "Lenovo",
    category: "Creator & Design",
    price: 16799000,
    oldPrice: 17999000,
    rating: 4.8,
    reviews: 79,
    stock: 7,
    badges: ["Ryzen 7 HS", "2.8K 120Hz"],
    image: "/images/products/lenovo-07/1.jpg",
    gallery: ["/images/products/lenovo-07/1.jpg", "/images/products/lenovo-07/2.jpg"],
    warranty: "2 years official Lenovo Premium Care + ADP",
    description: "Creative powerhouse with 8-core AMD Ryzen 7 7840HS processor, Radeon 780M graphics, and calibrated 2.8K 120Hz IPS display.",
    specs: {
      processor: "AMD Ryzen 7 7840HS",
      ram: "16GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "AMD Radeon 780M",
      screenSize: "14.5\"",
      resolution: "2.8K (2944 x 1840)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "73Wh \u2014 up to 12 hours",
      weight: "1.49 kg",
      warranty: "2 years official Lenovo Premium Care + ADP",
      usage: "Creator",
      screen: "14.5\" 2.8K IPS 120Hz 100% sRGB",
    },
    sold: 88,
    active: true,
    createdAt: "2026-08-07",
  },
  {
    id: "lenovo-08",
    name: "Lenovo Yoga Pro 9i 16IRH8",
    brand: "Lenovo",
    category: "Creator & Design",
    price: 33999000,
    oldPrice: 36499000,
    rating: 4.9,
    reviews: 55,
    stock: 4,
    badges: ["Mini-LED 3.2K", "RTX 4070 Studio"],
    image: "/images/products/lenovo-08/1.jpg",
    gallery: ["/images/products/lenovo-08/1.jpg"],
    warranty: "2 years official Lenovo Premium Care + ADP",
    description: "Top-tier content studio laptop with 3.2K 165Hz Mini-LED display (1200 nits), Intel Core i9-13905H, and NVIDIA Studio RTX 4070.",
    specs: {
      processor: "Intel Core i9-13905H",
      ram: "32GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4070 8GB Studio",
      screenSize: "16.0\"",
      resolution: "3.2K (3200 x 2000)",
      refreshRate: "165Hz",
      operatingSystem: "Windows 11 Home",
      battery: "75Wh \u2014 up to 9 hours",
      weight: "2.23 kg",
      warranty: "2 years official Lenovo Premium Care + ADP",
      usage: "Creator",
      screen: "16.0\" 3.2K Mini-LED 165Hz 1200nits HDR",
    },
    sold: 41,
    active: true,
    createdAt: "2026-08-08",
  },
  {
    id: "lenovo-09",
    name: "Lenovo LOQ 15IAX9",
    brand: "Lenovo",
    category: "Gaming Laptop",
    price: 12999000,
    oldPrice: 13999000,
    rating: 4.8,
    reviews: 175,
    stock: 12,
    badges: ["Top Gaming Value", "RTX 4050"],
    image: "/images/products/lenovo-09/1.jpg",
    gallery: ["/images/products/lenovo-09/1.jpg", "/images/products/lenovo-09/2.jpg", "/images/products/lenovo-09/3.jpg"],
    warranty: "2 years official Lenovo Premium Care + ADP",
    description: "Feature-packed budget gaming titan with RTX 4050 6GB, 100% sRGB 144Hz display, and LA1 AI chip for optimal thermal and frame rate management.",
    specs: {
      processor: "Intel Core i5-12450HX",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "144Hz",
      operatingSystem: "Windows 11 Home",
      battery: "60Wh \u2014 up to 6 hours",
      weight: "2.38 kg",
      warranty: "2 years official Lenovo Premium Care + ADP",
      usage: "Gaming",
      screen: "15.6\" FHD 144Hz 100% sRGB G-Sync",
    },
    sold: 310,
    active: true,
    createdAt: "2026-08-09",
  },
  {
    id: "lenovo-10",
    name: "Lenovo Legion 5i 16IRX9",
    brand: "Lenovo",
    category: "Gaming Laptop",
    price: 22499000,
    oldPrice: 23999000,
    rating: 4.9,
    reviews: 140,
    stock: 7,
    badges: ["Legion Coldfront", "RTX 4060 140W"],
    image: "/images/products/lenovo-10/1.jpg",
    gallery: ["/images/products/lenovo-10/1.jpg", "/images/products/lenovo-10/2.jpg"],
    warranty: "3 years official Lenovo Legion Ultimate Support + ADP",
    description: "High-performance esports laptop with Intel Core i7 14th Gen, full-power 140W RTX 4060 GPU, Legion Coldfront 5.0 cooling, and 2.5K 165Hz display.",
    specs: {
      processor: "Intel Core i7-14650HX",
      ram: "32GB DDR5 5600MHz",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4060 8GB (140W)",
      screenSize: "16.0\"",
      resolution: "2.5K WQXGA (2560 x 1600)",
      refreshRate: "165Hz",
      operatingSystem: "Windows 11 Home",
      battery: "80Wh \u2014 up to 7 hours",
      weight: "2.30 kg",
      warranty: "3 years official Lenovo Legion Ultimate Support + ADP",
      usage: "Gaming",
      screen: "16.0\" 2.5K WQXGA 165Hz 100% sRGB G-Sync",
    },
    sold: 160,
    active: true,
    createdAt: "2026-08-10",
  },
  {
    id: "acer-01",
    name: "Acer Aspire 3 Spin 14 A3SP14",
    brand: "Acer",
    category: "Student Laptop",
    price: 6499000,
    oldPrice: 6999000,
    rating: 4.6,
    reviews: 105,
    stock: 14,
    badges: ["Convertible 360", "Touchscreen"],
    image: "/images/products/acer-01/1.jpg",
    gallery: ["/images/products/acer-01/1.jpg", "/images/products/acer-01/2.jpg", "/images/products/acer-01/3.jpg"],
    warranty: "2 years official Acer warranty",
    description: "Versatile 2-in-1 convertible touchscreen laptop with 360-degree hinge, powered by 8-core Intel Core i3-N305 for study, note-taking, and media.",
    specs: {
      processor: "Intel Core i3-N305",
      ram: "8GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel UHD Graphics",
      screenSize: "14.0\"",
      resolution: "WUXGA (1920 x 1200)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "40Wh \u2014 up to 8 hours",
      weight: "1.50 kg",
      warranty: "2 years official Acer warranty",
      usage: "Student",
      screen: "14.0\" WUXGA IPS Touchscreen 360",
    },
    sold: 165,
    active: true,
    createdAt: "2026-08-01",
  },
  {
    id: "acer-02",
    name: "Acer Aspire Lite 14 AL14-51M",
    brand: "Acer",
    category: "Student Laptop",
    price: 5799000,
    oldPrice: 6299000,
    rating: 4.6,
    reviews: 120,
    stock: 15,
    badges: ["Budget Pick", "16:10 Screen"],
    image: "/images/products/acer-02/1.jpg",
    gallery: ["/images/products/acer-02/1.jpg", "/images/products/acer-02/2.jpg", "/images/products/acer-02/3.jpg"],
    warranty: "2 years official Acer warranty",
    description: "Lightweight and clean everyday laptop with Intel Core i3-1215U, 16:10 WUXGA screen, and fast PCIe SSD for smooth daily tasks.",
    specs: {
      processor: "Intel Core i3-1215U",
      ram: "8GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel UHD Graphics",
      screenSize: "14.0\"",
      resolution: "WUXGA (1920 x 1200)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "45Wh \u2014 up to 8 hours",
      weight: "1.35 kg",
      warranty: "2 years official Acer warranty",
      usage: "Student",
      screen: "14.0\" WUXGA 16:10 IPS Anti-Glare",
    },
    sold: 190,
    active: true,
    createdAt: "2026-08-02",
  },
  {
    id: "acer-03",
    name: "Acer Aspire 5 Slim A514-56P",
    brand: "Acer",
    category: "Coding & Programming",
    price: 8799000,
    oldPrice: 9499000,
    rating: 4.7,
    reviews: 110,
    stock: 10,
    badges: ["Reliable", "16GB RAM"],
    image: "/images/products/acer-03/1.jpg",
    gallery: ["/images/products/acer-03/1.jpg", "/images/products/acer-03/2.jpg", "/images/products/acer-03/3.jpg"],
    warranty: "2 years official Acer warranty",
    description: "Essential coding notebook featuring 13th Gen Intel Core i5-1335U, 16GB RAM, and crisp FHD display with Acer TNR noise reduction for crystal clear calls.",
    specs: {
      processor: "Intel Core i5-1335U",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "50Wh \u2014 up to 9 hours",
      weight: "1.48 kg",
      warranty: "2 years official Acer warranty",
      usage: "Coding",
      screen: "14.0\" FHD IPS ComfyView",
    },
    sold: 155,
    active: true,
    createdAt: "2026-08-03",
  },
  {
    id: "acer-04",
    name: "Acer Swift Go 14 AI SFG14-73",
    brand: "Acer",
    category: "Coding & Programming",
    price: 14499000,
    oldPrice: 15499000,
    rating: 4.8,
    reviews: 90,
    stock: 8,
    badges: ["Intel Core Ultra", "2.8K OLED 90Hz"],
    image: "/images/products/acer-04/1.jpg",
    gallery: ["/images/products/acer-04/1.jpg", "/images/products/acer-04/2.jpg", "/images/products/acer-04/3.jpg"],
    warranty: "2 years official Acer warranty + 1 year ADP",
    description: "Thin-and-light AI ultrabook with Intel Core Ultra 7 155H, 2.8K 90Hz OLED display (100% DCI-P3), and dual fans with TwinAir technology.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "16GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "90Hz",
      operatingSystem: "Windows 11 Home",
      battery: "65Wh \u2014 up to 13 hours",
      weight: "1.32 kg",
      warranty: "2 years official Acer warranty + 1 year ADP",
      usage: "Coding",
      screen: "14.0\" 2.8K OLED 90Hz 500nits HDR",
    },
    sold: 105,
    active: true,
    createdAt: "2026-08-04",
  },
  {
    id: "acer-05",
    name: "Acer Swift Edge 16 SFE16-43",
    brand: "Acer",
    category: "Business Laptop",
    price: 17999000,
    oldPrice: 19299000,
    rating: 4.9,
    reviews: 68,
    stock: 6,
    badges: ["Ultra Light 1.23kg", "3.2K 120Hz OLED"],
    image: "/images/products/acer-05/1.jpg",
    gallery: ["/images/products/acer-05/1.jpg", "/images/products/acer-05/2.jpg", "/images/products/acer-05/3.jpg"],
    warranty: "2 years official Acer warranty + 1 year ADP",
    description: "World's lightest 16-inch laptop crafted from magnesium-aluminum alloy weighing only 1.23kg, with 3.2K 120Hz OLED and Ryzen 7 7840U.",
    specs: {
      processor: "AMD Ryzen 7 7840U",
      ram: "16GB LPDDR5",
      storage: "1TB NVMe SSD",
      gpu: "AMD Radeon 780M",
      screenSize: "16.0\"",
      resolution: "3.2K (3200 x 2000)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "54Wh \u2014 up to 10 hours",
      weight: "1.23 kg",
      warranty: "2 years official Acer warranty + 1 year ADP",
      usage: "Business",
      screen: "16.0\" 3.2K OLED 120Hz 0.2ms 500nits",
    },
    sold: 72,
    active: true,
    createdAt: "2026-08-05",
  },
  {
    id: "acer-06",
    name: "Acer Swift X 14 SFX14-72G",
    brand: "Acer",
    category: "Creator & Design",
    price: 21999000,
    oldPrice: 23499000,
    rating: 4.9,
    reviews: 75,
    stock: 6,
    badges: ["RTX 4060", "Calman Verified"],
    image: "/images/products/acer-06/1.jpg",
    gallery: ["/images/products/acer-06/1.jpg", "/images/products/acer-06/2.jpg", "/images/products/acer-06/3.jpg"],
    warranty: "2 years official Acer warranty + 1 year ADP",
    description: "Ultra-portable creator laptop with NVIDIA GeForce RTX 4060, Intel Core Ultra 7 155H, 32GB RAM, and 120Hz 2.8K OLED display.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "32GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      screenSize: "14.5\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "76Wh \u2014 up to 11 hours",
      weight: "1.55 kg",
      warranty: "2 years official Acer warranty + 1 year ADP",
      usage: "Creator",
      screen: "14.5\" 2.8K OLED 120Hz Calman Verified",
    },
    sold: 68,
    active: true,
    createdAt: "2026-08-06",
  },
  {
    id: "acer-07",
    name: "Acer TravelMate P2 TMP214-54",
    brand: "Acer",
    category: "Business Laptop",
    price: 10299000,
    oldPrice: 11299000,
    rating: 4.7,
    reviews: 58,
    stock: 11,
    badges: ["Enterprise", "Windows 11 Pro"],
    image: "/images/products/acer-07/1.jpg",
    gallery: ["/images/products/acer-07/1.jpg", "/images/products/acer-07/2.jpg"],
    warranty: "3 years official Acer Commercial warranty",
    description: "Reliable corporate commercial notebook with MIL-STD-810H durability, TPM 2.0 security, and Windows 11 Pro.",
    specs: {
      processor: "Intel Core i5-1235U",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "50Wh \u2014 up to 9 hours",
      weight: "1.60 kg",
      warranty: "3 years official Acer Commercial warranty",
      usage: "Business",
      screen: "14.0\" FHD IPS Anti-Glare",
    },
    sold: 85,
    active: true,
    createdAt: "2026-08-07",
  },
  {
    id: "acer-08",
    name: "Acer Nitro V 15 ANV15-51",
    brand: "Acer",
    category: "Gaming Laptop",
    price: 13299000,
    oldPrice: 14199000,
    rating: 4.8,
    reviews: 180,
    stock: 11,
    badges: ["Best Seller", "RTX 4050"],
    image: "/images/products/acer-08/1.jpg",
    gallery: ["/images/products/acer-08/1.jpg", "/images/products/acer-08/2.jpg"],
    warranty: "2 years official Acer warranty + 1 year ADP",
    description: "Budget gaming beast with 13th Gen Intel Core i5, NVIDIA GeForce RTX 4050 6GB, and 144Hz high refresh rate screen.",
    specs: {
      processor: "Intel Core i5-13420H",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "144Hz",
      operatingSystem: "Windows 11 Home",
      battery: "57Wh \u2014 up to 6 hours",
      weight: "2.10 kg",
      warranty: "2 years official Acer warranty + 1 year ADP",
      usage: "Gaming",
      screen: "15.6\" FHD 144Hz IPS",
    },
    sold: 275,
    active: true,
    createdAt: "2026-08-08",
  },
  {
    id: "acer-09",
    name: "Acer Nitro 16 AN16-41",
    brand: "Acer",
    category: "Gaming Laptop",
    price: 18499000,
    oldPrice: 19999000,
    rating: 4.9,
    reviews: 125,
    stock: 8,
    badges: ["WQXGA 165Hz", "Liquid Metal"],
    image: "/images/products/acer-09/1.jpg",
    gallery: ["/images/products/acer-09/1.jpg", "/images/products/acer-09/2.jpg", "/images/products/acer-09/3.jpg"],
    warranty: "2 years official Acer warranty + 1 year ADP",
    description: "Equipped with AMD Ryzen 7 7840HS, liquid metal thermal interface, full-power 140W RTX 4060 GPU, and stunning 16-inch WQXGA 165Hz display.",
    specs: {
      processor: "AMD Ryzen 7 7840HS",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4060 8GB (140W)",
      screenSize: "16.0\"",
      resolution: "WQXGA (2560 x 1600)",
      refreshRate: "165Hz",
      operatingSystem: "Windows 11 Home",
      battery: "90Wh \u2014 up to 8 hours",
      weight: "2.70 kg",
      warranty: "2 years official Acer warranty + 1 year ADP",
      usage: "Gaming",
      screen: "16.0\" WQXGA 165Hz 100% sRGB G-Sync",
    },
    sold: 150,
    active: true,
    createdAt: "2026-08-09",
  },
  {
    id: "acer-10",
    name: "Acer Predator Helios Neo 16 PHN16-72",
    brand: "Acer",
    category: "Gaming Laptop",
    price: 29999000,
    oldPrice: 31999000,
    rating: 4.9,
    reviews: 88,
    stock: 5,
    badges: ["Predator Flagship", "240Hz Display"],
    image: "/images/products/acer-10/1.jpg",
    gallery: ["/images/products/acer-10/1.jpg", "/images/products/acer-10/2.jpg", "/images/products/acer-10/3.jpg"],
    warranty: "3 years official Acer Onsite warranty + 1 year ADP",
    description: "Hardcore gaming flagship powered by 24-core Intel Core i9-14900HX, RTX 4070 8GB, 5th Gen AeroBlade 3D fans, and 240Hz 3ms screen.",
    specs: {
      processor: "Intel Core i9-14900HX",
      ram: "32GB DDR5 5600MHz",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4070 8GB",
      screenSize: "16.0\"",
      resolution: "WQXGA (2560 x 1600)",
      refreshRate: "240Hz",
      operatingSystem: "Windows 11 Home",
      battery: "90Wh \u2014 up to 7 hours",
      weight: "2.60 kg",
      warranty: "3 years official Acer Onsite warranty + 1 year ADP",
      usage: "Gaming",
      screen: "16.0\" WQXGA 240Hz 3ms 500nits 100% DCI-P3",
    },
    sold: 80,
    active: true,
    createdAt: "2026-08-10",
  },
  {
    id: "hp-01",
    name: "HP 14s-dq5115TU",
    brand: "HP",
    category: "Student Laptop",
    price: 6199000,
    oldPrice: 6699000,
    rating: 4.6,
    reviews: 135,
    stock: 14,
    badges: ["Student Favorite", "FHD IPS"],
    image: "/images/products/hp-01/1.png",
    gallery: ["/images/products/hp-01/1.png", "/images/products/hp-01/2.jpg", "/images/products/hp-01/3.jpg"],
    warranty: "2 years official HP warranty",
    description: "Clean and reliable 14-inch everyday laptop with Intel Core i3-1215U, FHD IPS display, and fast charging technology.",
    specs: {
      processor: "Intel Core i3-1215U",
      ram: "8GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel UHD Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "41Wh \u2014 up to 8 hours",
      weight: "1.46 kg",
      warranty: "2 years official HP warranty",
      usage: "Student",
      screen: "14.0\" FHD IPS micro-edge Anti-Glare",
    },
    sold: 220,
    active: true,
    createdAt: "2026-08-01",
  },
  {
    id: "hp-02",
    name: "HP 14s-em0014AU",
    brand: "HP",
    category: "Student Laptop",
    price: 7699000,
    oldPrice: 8299000,
    rating: 4.7,
    reviews: 115,
    stock: 12,
    badges: ["16GB RAM", "Ryzen 5"],
    image: "/images/products/hp-02/1.jpg",
    gallery: ["/images/products/hp-02/1.jpg", "/images/products/hp-02/2.jpg", "/images/products/hp-02/3.jpg"],
    warranty: "2 years official HP warranty",
    description: "Smooth daily multitasking laptop featuring AMD Ryzen 5 7520U with 16GB RAM and long battery life.",
    specs: {
      processor: "AMD Ryzen 5 7520U",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "AMD Radeon 610M",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "41Wh \u2014 up to 9 hours",
      weight: "1.40 kg",
      warranty: "2 years official HP warranty",
      usage: "Student",
      screen: "14.0\" FHD micro-edge Anti-Glare",
    },
    sold: 180,
    active: true,
    createdAt: "2026-08-02",
  },
  {
    id: "hp-03",
    name: "HP Pavilion Plus 14-ew0015TU",
    brand: "HP",
    category: "Coding & Programming",
    price: 13499000,
    oldPrice: 14499000,
    rating: 4.8,
    reviews: 88,
    stock: 9,
    badges: ["2.8K OLED", "Intel Core Ultra"],
    image: "/images/products/hp-03/1.jpg",
    gallery: ["/images/products/hp-03/1.jpg", "/images/products/hp-03/2.jpg", "/images/products/hp-03/3.jpg"],
    warranty: "2 years official HP warranty + ADP",
    description: "Sleek all-metal ultrabook with 2.8K 120Hz OLED screen, Intel Core Ultra 5 125H, and 5MP IR webcam with AI noise reduction.",
    specs: {
      processor: "Intel Core Ultra 5 125H",
      ram: "16GB LPDDR5X",
      storage: "512GB NVMe SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "68Wh \u2014 up to 12 hours",
      weight: "1.44 kg",
      warranty: "2 years official HP warranty + ADP",
      usage: "Coding",
      screen: "14.0\" 2.8K OLED 120Hz HDR 500nits",
    },
    sold: 120,
    active: true,
    createdAt: "2026-08-03",
  },
  {
    id: "hp-04",
    name: "HP Envy x360 14-fa0018AU",
    brand: "HP",
    category: "Creator & Design",
    price: 17499000,
    oldPrice: 18799000,
    rating: 4.9,
    reviews: 75,
    stock: 7,
    badges: ["2-in-1 Touch", "2.8K OLED 120Hz"],
    image: "/images/products/hp-04/1.jpg",
    gallery: ["/images/products/hp-04/1.jpg", "/images/products/hp-04/2.jpg", "/images/products/hp-04/3.jpg"],
    warranty: "2 years official HP warranty + ADP",
    description: "Premium 2-in-1 convertible creator laptop with 2.8K 120Hz OLED touch display, AMD Ryzen 7 8840HS with Ryzen AI, and HP MPP2.0 tilt pen included.",
    specs: {
      processor: "AMD Ryzen 7 8840HS",
      ram: "16GB LPDDR5",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "AMD Radeon 780M",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "59Wh \u2014 up to 12 hours",
      weight: "1.39 kg",
      warranty: "2 years official HP warranty + ADP",
      usage: "Creator",
      screen: "14.0\" 2.8K OLED Touch 120Hz 500nits",
    },
    sold: 92,
    active: true,
    createdAt: "2026-08-04",
  },
  {
    id: "hp-05",
    name: "HP Spectre x360 14-eu0005TU",
    brand: "HP",
    category: "Creator & Design",
    price: 26999000,
    oldPrice: 28999000,
    rating: 4.9,
    reviews: 65,
    stock: 5,
    badges: ["Flagship Luxury", "9MP AI Camera"],
    image: "/images/products/hp-05/1.jpg",
    gallery: ["/images/products/hp-05/1.jpg", "/images/products/hp-05/2.jpg", "/images/products/hp-05/3.jpg"],
    warranty: "2 years official HP Onsite warranty + ADP",
    description: "Luxurious gem-cut convertible with Intel Core Ultra 7, 32GB RAM, industry-first 9MP AI camera with auto-framing, and 2.8K OLED touch.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "32GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "68Wh \u2014 up to 14 hours",
      weight: "1.44 kg",
      warranty: "2 years official HP Onsite warranty + ADP",
      usage: "Creator",
      screen: "14.0\" 2.8K OLED Touch 120Hz HDR (9MP AI Camera)",
    },
    sold: 55,
    active: true,
    createdAt: "2026-08-05",
  },
  {
    id: "hp-06",
    name: "HP ProBook 440 G10",
    brand: "HP",
    category: "Business Laptop",
    price: 11999000,
    oldPrice: 12899000,
    rating: 4.8,
    reviews: 82,
    stock: 12,
    badges: ["Wolf Security", "Windows 11 Pro"],
    image: "/images/products/hp-06/1.jpg",
    gallery: ["/images/products/hp-06/1.jpg", "/images/products/hp-06/2.jpg", "/images/products/hp-06/3.jpg"],
    warranty: "3 years official HP Onsite warranty",
    description: "Commercial business laptop with HP Wolf Pro Security Edition, spill-resistant keyboard, Intel Core i5-1335U, and Windows 11 Pro.",
    specs: {
      processor: "Intel Core i5-1335U",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "51Wh \u2014 up to 10 hours",
      weight: "1.38 kg",
      warranty: "3 years official HP Onsite warranty",
      usage: "Business",
      screen: "14.0\" FHD IPS Anti-Glare 400nits",
    },
    sold: 110,
    active: true,
    createdAt: "2026-08-06",
  },
  {
    id: "hp-07",
    name: "HP EliteBook 840 G10",
    brand: "HP",
    category: "Business Laptop",
    price: 23899000,
    oldPrice: 25499000,
    rating: 4.9,
    reviews: 54,
    stock: 6,
    badges: ["Intel vPro", "Enterprise Flagship"],
    image: "/images/products/hp-07/1.jpg",
    gallery: ["/images/products/hp-07/1.jpg", "/images/products/hp-07/2.jpg", "/images/products/hp-07/3.jpg"],
    warranty: "3 years official HP Onsite Premier warranty",
    description: "Enterprise-grade elite laptop with Intel Core i7-1365U vPro, 32GB RAM, 5MP IR auto-tracking camera, and multi-layered hardware security.",
    specs: {
      processor: "Intel Core i7-1365U vPro",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "WUXGA (1920 x 1200)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "51Wh \u2014 up to 13 hours",
      weight: "1.36 kg",
      warranty: "3 years official HP Onsite Premier warranty",
      usage: "Business",
      screen: "14.0\" WUXGA 16:10 IPS 400nits HP Sure View",
    },
    sold: 60,
    active: true,
    createdAt: "2026-08-07",
  },
  {
    id: "hp-08",
    name: "HP Victus 15-fa1168TX",
    brand: "HP",
    category: "Gaming Laptop",
    price: 11999000,
    oldPrice: 12799000,
    rating: 4.8,
    reviews: 160,
    stock: 11,
    badges: ["Best Seller", "144Hz Gaming"],
    image: "/images/products/hp-08/1.jpg",
    gallery: ["/images/products/hp-08/1.jpg", "/images/products/hp-08/2.png", "/images/products/hp-08/3.png"],
    warranty: "2 years official HP warranty + ADP",
    description: "Popular gaming laptop with Intel Core i5-13420H, RTX 3050 6GB GPU, and 144Hz FHD gaming display with OMEN Gaming Hub optimization.",
    specs: {
      processor: "Intel Core i5-13420H",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 3050 6GB",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "144Hz",
      operatingSystem: "Windows 11 Home",
      battery: "70Wh \u2014 up to 7 hours",
      weight: "2.29 kg",
      warranty: "2 years official HP warranty + ADP",
      usage: "Gaming",
      screen: "15.6\" FHD 144Hz IPS 9ms",
    },
    sold: 260,
    active: true,
    createdAt: "2026-08-08",
  },
  {
    id: "hp-09",
    name: "HP Victus 16-r1089TX",
    brand: "HP",
    category: "Gaming Laptop",
    price: 19499000,
    oldPrice: 20999000,
    rating: 4.9,
    reviews: 110,
    stock: 7,
    badges: ["Core i7 14th Gen", "RTX 4060 120W"],
    image: "/images/products/hp-09/1.png",
    gallery: ["/images/products/hp-09/1.png", "/images/products/hp-09/2.png"],
    warranty: "2 years official HP warranty + ADP",
    description: "High-powered 16.1-inch gaming rig with 14th Gen Intel Core i7-14700HX (20 cores), 120W RTX 4060, and 165Hz 100% sRGB screen.",
    specs: {
      processor: "Intel Core i7-14700HX",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4060 8GB (120W)",
      screenSize: "16.1\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "165Hz",
      operatingSystem: "Windows 11 Home",
      battery: "83Wh \u2014 up to 8 hours",
      weight: "2.33 kg",
      warranty: "2 years official HP warranty + ADP",
      usage: "Gaming",
      screen: "16.1\" FHD 165Hz 100% sRGB 7ms",
    },
    sold: 135,
    active: true,
    createdAt: "2026-08-09",
  },
  {
    id: "hp-10",
    name: "HP Omen 16-wf1027TX",
    brand: "HP",
    category: "Gaming Laptop",
    price: 32999000,
    oldPrice: 35499000,
    rating: 4.9,
    reviews: 70,
    stock: 5,
    badges: ["OMEN Flagship", "240Hz 3ms"],
    image: "/images/products/hp-10/1.jpg",
    gallery: ["/images/products/hp-10/1.jpg", "/images/products/hp-10/2.jpg", "/images/products/hp-10/3.jpg"],
    warranty: "2 years official HP Onsite warranty + ADP",
    description: "Top-of-the-line gaming flagship featuring 24-core Intel Core i9-14900HX, 140W RTX 4070, OMEN Tempest Cooling, and 240Hz QHD display.",
    specs: {
      processor: "Intel Core i9-14900HX",
      ram: "32GB DDR5 5600MHz",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4070 8GB (140W)",
      screenSize: "16.1\"",
      resolution: "QHD (2560 x 1440)",
      refreshRate: "240Hz",
      operatingSystem: "Windows 11 Home",
      battery: "83Wh \u2014 up to 7 hours",
      weight: "2.39 kg",
      warranty: "2 years official HP Onsite warranty + ADP",
      usage: "Gaming",
      screen: "16.1\" QHD 240Hz 3ms 100% sRGB G-Sync",
    },
    sold: 68,
    active: true,
    createdAt: "2026-08-10",
  },
  {
    id: "dell-01",
    name: "Dell Inspiron 14 3420",
    brand: "Dell",
    category: "Student Laptop",
    price: 5699000,
    oldPrice: 6199000,
    rating: 4.5,
    reviews: 115,
    stock: 14,
    badges: ["Value Pick", "Daily Study"],
    image: "/images/products/dell-01/1.jpg",
    gallery: ["/images/products/dell-01/1.jpg", "/images/products/dell-01/2.jpg"],
    warranty: "2 years official Dell Premium Support Onsite",
    description: "Dependable 14-inch daily laptop powered by Intel Core i3-1115G4, sturdy carbon black chassis, and responsive NVMe SSD.",
    specs: {
      processor: "Intel Core i3-1115G4",
      ram: "8GB DDR4",
      storage: "256GB NVMe SSD",
      gpu: "Intel UHD Graphics",
      screenSize: "14.0\"",
      resolution: "HD (1366 x 768)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "41Wh \u2014 up to 7 hours",
      weight: "1.48 kg",
      warranty: "2 years official Dell Premium Support Onsite",
      usage: "Student",
      screen: "14.0\" HD Anti-Glare LED Backlight",
    },
    sold: 190,
    active: true,
    createdAt: "2026-08-01",
  },
  {
    id: "dell-02",
    name: "Dell Inspiron 14 5430",
    brand: "Dell",
    category: "Coding & Programming",
    price: 9999000,
    oldPrice: 10799000,
    rating: 4.7,
    reviews: 96,
    stock: 10,
    badges: ["16:10 Screen", "Dell Cinema"],
    image: "/images/products/dell-02/1.jpg",
    gallery: ["/images/products/dell-02/1.jpg", "/images/products/dell-02/2.jpg", "/images/products/dell-02/3.jpg"],
    warranty: "2 years official Dell Premium Support Onsite",
    description: "Modern metal-chassis laptop with 16:10 WUXGA display, Intel Core i5-1335U, Waves MaxxAudio Pro speakers, and express charge.",
    specs: {
      processor: "Intel Core i5-1335U",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "WUXGA (1920 x 1200)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "54Wh \u2014 up to 9 hours",
      weight: "1.53 kg",
      warranty: "2 years official Dell Premium Support Onsite",
      usage: "Coding",
      screen: "14.0\" WUXGA 16:10 IPS Anti-Glare",
    },
    sold: 145,
    active: true,
    createdAt: "2026-08-02",
  },
  {
    id: "dell-03",
    name: "Dell Inspiron 16 Plus 7630",
    brand: "Dell",
    category: "Creator & Design",
    price: 16999000,
    oldPrice: 18299000,
    rating: 4.8,
    reviews: 72,
    stock: 8,
    badges: ["2.5K Screen", "RTX 3050 6GB"],
    image: "/images/products/dell-03/1.jpg",
    gallery: ["/images/products/dell-03/1.jpg", "/images/products/dell-03/2.jpg", "/images/products/dell-03/3.jpg"],
    warranty: "2 years official Dell Premium Support Onsite",
    description: "High-powered 16-inch creator laptop with 2.5K 16:10 display, Intel Core i7-13700H, dedicated RTX 3050 graphics, and quad speakers.",
    specs: {
      processor: "Intel Core i7-13700H",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 3050 6GB",
      screenSize: "16.0\"",
      resolution: "2.5K (2560 x 1600)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "86Wh \u2014 up to 11 hours",
      weight: "2.06 kg",
      warranty: "2 years official Dell Premium Support Onsite",
      usage: "Creator",
      screen: "16.0\" 2.5K 16:10 IPS 300nits 100% sRGB",
    },
    sold: 88,
    active: true,
    createdAt: "2026-08-03",
  },
  {
    id: "dell-04",
    name: "Dell Latitude 3440",
    brand: "Dell",
    category: "Business Laptop",
    price: 11499000,
    oldPrice: 12499000,
    rating: 4.8,
    reviews: 78,
    stock: 11,
    badges: ["Business Standard", "Windows 11 Pro"],
    image: "/images/products/dell-04/1.jpg",
    gallery: ["/images/products/dell-04/1.jpg", "/images/products/dell-04/2.jpg"],
    warranty: "3 years official Dell ProSupport Onsite",
    description: "Workplace-ready commercial laptop with Intel Core i5-1335U, TPM 2.0 security, ExpressResponse app optimizer, and Windows 11 Pro.",
    specs: {
      processor: "Intel Core i5-1335U",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "54Wh \u2014 up to 10 hours",
      weight: "1.54 kg",
      warranty: "3 years official Dell ProSupport Onsite",
      usage: "Business",
      screen: "14.0\" FHD IPS Anti-Glare 250nits",
    },
    sold: 125,
    active: true,
    createdAt: "2026-08-04",
  },
  {
    id: "dell-05",
    name: "Dell Latitude 5440",
    brand: "Dell",
    category: "Business Laptop",
    price: 16499000,
    oldPrice: 17899000,
    rating: 4.9,
    reviews: 62,
    stock: 9,
    badges: ["Intel vPro", "Enterprise Security"],
    image: "/images/products/dell-05/1.jpg",
    gallery: ["/images/products/dell-05/1.jpg", "/images/products/dell-05/2.jpg"],
    warranty: "3 years official Dell ProSupport Next Business Day Onsite",
    description: "Secure corporate laptop built with sustainable bio-based materials, Intel Core i7-1365U vPro, DDR5 memory, and advanced hardware security.",
    specs: {
      processor: "Intel Core i7-1365U vPro",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "54Wh \u2014 up to 12 hours",
      weight: "1.36 kg",
      warranty: "3 years official Dell ProSupport Next Business Day Onsite",
      usage: "Business",
      screen: "14.0\" FHD IPS Anti-Glare 300nits",
    },
    sold: 90,
    active: true,
    createdAt: "2026-08-05",
  },
  {
    id: "dell-06",
    name: "Dell XPS 13 9340 (2026)",
    brand: "Dell",
    category: "Coding & Programming",
    price: 28999000,
    oldPrice: 30999000,
    rating: 4.9,
    reviews: 58,
    stock: 6,
    badges: ["Futuristic Design", "3K+ OLED Touch"],
    image: "/images/products/dell-06/1.jpg",
    gallery: ["/images/products/dell-06/1.jpg", "/images/products/dell-06/2.jpg"],
    warranty: "2 years official Dell Premium Support Plus",
    description: "Iconic futuristic ultrabook with seamless glass touchpad, capacitive touch function row, 3K+ OLED InfinityEdge display, and Intel Core Ultra 7.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "32GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "13.4\"",
      resolution: "3K+ (2880 x 1800)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "55Wh \u2014 up to 13 hours",
      weight: "1.19 kg",
      warranty: "2 years official Dell Premium Support Plus",
      usage: "Coding",
      screen: "13.4\" 3K+ OLED InfinityEdge Touch 400nits",
    },
    sold: 52,
    active: true,
    createdAt: "2026-08-06",
  },
  {
    id: "dell-07",
    name: "Dell XPS 14 9440",
    brand: "Dell",
    category: "Creator & Design",
    price: 34499000,
    oldPrice: 36999000,
    rating: 4.9,
    reviews: 46,
    stock: 5,
    badges: ["3.2K OLED 120Hz", "RTX 4050"],
    image: "/images/products/dell-07/1.jpg",
    gallery: ["/images/products/dell-07/1.jpg", "/images/products/dell-07/2.jpg", "/images/products/dell-07/3.jpg", "/images/products/dell-07/4.jpg"],
    warranty: "2 years official Dell Premium Support Plus",
    description: "Premium CNC machined aluminum studio laptop with 3.2K 120Hz OLED touch display, NVIDIA GeForce RTX 4050, and 32GB RAM for creative pros.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "32GB LPDDR5X",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      screenSize: "14.5\"",
      resolution: "3.2K (3200 x 2000)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "70Wh \u2014 up to 11 hours",
      weight: "1.68 kg",
      warranty: "2 years official Dell Premium Support Plus",
      usage: "Creator",
      screen: "14.5\" 3.2K OLED Touch 120Hz 500nits HDR",
    },
    sold: 38,
    active: true,
    createdAt: "2026-08-07",
  },
  {
    id: "dell-08",
    name: "Dell G15 5530",
    brand: "Dell",
    category: "Gaming Laptop",
    price: 12499000,
    oldPrice: 13499000,
    rating: 4.8,
    reviews: 145,
    stock: 10,
    badges: ["Retro Design", "Alienware Cooling"],
    image: "/images/products/dell-08/1.jpg",
    gallery: ["/images/products/dell-08/1.jpg", "/images/products/dell-08/2.jpg"],
    warranty: "2 years official Dell Premium Support Onsite",
    description: "Alienware-inspired thermal design with Intel Core i5-13450HX, RTX 3050 6GB, retro two-tone styling, and 120Hz gaming display.",
    specs: {
      processor: "Intel Core i5-13450HX",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 3050 6GB",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "56Wh \u2014 up to 6 hours",
      weight: "2.65 kg",
      warranty: "2 years official Dell Premium Support Onsite",
      usage: "Gaming",
      screen: "15.6\" FHD 120Hz 250nits Anti-Glare",
    },
    sold: 210,
    active: true,
    createdAt: "2026-08-08",
  },
  {
    id: "dell-09",
    name: "Dell G15 5535",
    brand: "Dell",
    category: "Gaming Laptop",
    price: 17999000,
    oldPrice: 19499000,
    rating: 4.9,
    reviews: 98,
    stock: 8,
    badges: ["RTX 4060 140W", "165Hz sRGB"],
    image: "/images/products/dell-09/1.jpg",
    gallery: ["/images/products/dell-09/1.jpg", "/images/products/dell-09/2.jpg"],
    warranty: "2 years official Dell Premium Support Onsite",
    description: "Heavy-duty gaming machine featuring AMD Ryzen 7 7840HS, 140W RTX 4060 8GB GPU, and high-accuracy 165Hz 100% sRGB display.",
    specs: {
      processor: "AMD Ryzen 7 7840HS",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4060 8GB (140W)",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "165Hz",
      operatingSystem: "Windows 11 Home",
      battery: "86Wh \u2014 up to 8 hours",
      weight: "2.81 kg",
      warranty: "2 years official Dell Premium Support Onsite",
      usage: "Gaming",
      screen: "15.6\" FHD 165Hz 100% sRGB G-Sync",
    },
    sold: 130,
    active: true,
    createdAt: "2026-08-09",
  },
  {
    id: "dell-10",
    name: "Dell Alienware m16 R2",
    brand: "Dell",
    category: "Gaming Laptop",
    price: 35999000,
    oldPrice: 38499000,
    rating: 4.9,
    reviews: 68,
    stock: 4,
    badges: ["Alienware Flagship", "QHD+ 240Hz"],
    image: "/images/products/dell-10/1.jpg",
    gallery: ["/images/products/dell-10/1.jpg", "/images/products/dell-10/2.jpg"],
    warranty: "3 years official Dell Alienware Support Onsite",
    description: "Redesigned Alienware m16 R2 with Stealth Mode, Cryo-tech cooling, Intel Core Ultra 7, 140W RTX 4070, and ultra-smooth QHD+ 240Hz panel.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "32GB DDR5 5600MHz",
      storage: "1TB NVMe PCIe 4.0 SSD",
      gpu: "NVIDIA GeForce RTX 4070 8GB (140W)",
      screenSize: "16.0\"",
      resolution: "QHD+ (2560 x 1600)",
      refreshRate: "240Hz",
      operatingSystem: "Windows 11 Home",
      battery: "90Wh \u2014 up to 8 hours",
      weight: "2.61 kg",
      warranty: "3 years official Dell Alienware Support Onsite",
      usage: "Gaming",
      screen: "16.0\" QHD+ 240Hz 3ms 100% sRGB G-Sync",
    },
    sold: 60,
    active: true,
    createdAt: "2026-08-10",
  },
  {
    id: "msi-01",
    name: "MSI Modern 14 C12MO",
    brand: "MSI",
    category: "Student Laptop",
    price: 5899000,
    oldPrice: 6399000,
    rating: 4.6,
    reviews: 110,
    stock: 15,
    badges: ["Lightweight 1.4kg", "Type-C PD"],
    image: "/images/products/msi-01/1.png",
    gallery: ["/images/products/msi-01/1.png", "/images/products/msi-01/2.jpg"],
    warranty: "2 years official MSI warranty",
    description: "Ultra-portable 1.4kg laptop powered by Intel Core i3-1215U with 180-degree lay-flat hinge and Type-C power delivery.",
    specs: {
      processor: "Intel Core i3-1215U",
      ram: "8GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel UHD Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "39.3Wh \u2014 up to 7 hours",
      weight: "1.40 kg",
      warranty: "2 years official MSI warranty",
      usage: "Student",
      screen: "14.0\" FHD IPS-Level 60Hz",
    },
    sold: 185,
    active: true,
    createdAt: "2026-08-01",
  },
  {
    id: "msi-02",
    name: "MSI Modern 14 C13M",
    brand: "MSI",
    category: "Coding & Programming",
    price: 8499000,
    oldPrice: 9199000,
    rating: 4.7,
    reviews: 105,
    stock: 12,
    badges: ["Best Seller", "16GB RAM"],
    image: "/images/products/msi-02/1.jpg",
    gallery: ["/images/products/msi-02/1.jpg", "/images/products/msi-02/2.png"],
    warranty: "2 years official MSI warranty",
    description: "Versatile daily coding laptop with 13th Gen Intel Core i5-1335U, 16GB RAM, illuminated keyboard, and crisp FHD IPS-Level screen.",
    specs: {
      processor: "Intel Core i5-1335U",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "39.3Wh \u2014 up to 8 hours",
      weight: "1.40 kg",
      warranty: "2 years official MSI warranty",
      usage: "Coding",
      screen: "14.0\" FHD IPS-Level Anti-Glare",
    },
    sold: 160,
    active: true,
    createdAt: "2026-08-02",
  },
  {
    id: "msi-03",
    name: "MSI Modern 15 H B13M",
    brand: "MSI",
    category: "Coding & Programming",
    price: 10999000,
    oldPrice: 11999000,
    rating: 4.8,
    reviews: 80,
    stock: 10,
    badges: ["45W H-Series", "Full Numpad"],
    image: "/images/products/msi-03/1.jpg",
    gallery: ["/images/products/msi-03/1.jpg", "/images/products/msi-03/2.jpg", "/images/products/msi-03/3.jpg"],
    warranty: "2 years official MSI warranty",
    description: "High-performance productivity laptop featuring powerful 45W Intel Core i7-13620H processor, dedicated numpad, and DDR5 RAM.",
    specs: {
      processor: "Intel Core i7-13620H",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "53.8Wh \u2014 up to 8 hours",
      weight: "1.70 kg",
      warranty: "2 years official MSI warranty",
      usage: "Coding",
      screen: "15.6\" FHD IPS-Level (with Numpad)",
    },
    sold: 115,
    active: true,
    createdAt: "2026-08-03",
  },
  {
    id: "msi-04",
    name: "MSI Prestige 14 AI Evo C1MG",
    brand: "MSI",
    category: "Business Laptop",
    price: 18499000,
    oldPrice: 19799000,
    rating: 4.9,
    reviews: 65,
    stock: 7,
    badges: ["90Wh Battery", "2.8K OLED"],
    image: "/images/products/msi-04/1.jpg",
    gallery: ["/images/products/msi-04/1.jpg", "/images/products/msi-04/2.jpg", "/images/products/msi-04/3.webp"],
    warranty: "2 years official MSI warranty",
    description: "Executive ultrabook with massive 90Wh battery (up to 16h battery life), 2.8K OLED display, 32GB RAM, and Intel Core Ultra 7.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "32GB LPDDR5",
      storage: "1TB NVMe SSD",
      gpu: "Intel Arc Graphics",
      screenSize: "14.0\"",
      resolution: "2.8K (2880 x 1800)",
      refreshRate: "120Hz",
      operatingSystem: "Windows 11 Home",
      battery: "90Wh \u2014 up to 16 hours",
      weight: "1.70 kg",
      warranty: "2 years official MSI warranty",
      usage: "Business",
      screen: "14.0\" 2.8K OLED 120Hz 100% DCI-P3",
    },
    sold: 70,
    active: true,
    createdAt: "2026-08-04",
  },
  {
    id: "msi-05",
    name: "MSI Prestige 16 AI Studio B1VFG",
    brand: "MSI",
    category: "Creator & Design",
    price: 29499000,
    oldPrice: 31499000,
    rating: 4.9,
    reviews: 48,
    stock: 5,
    badges: ["4K UHD+ OLED", "RTX 4060 Studio"],
    image: "/images/products/msi-05/1.jpg",
    gallery: ["/images/products/msi-05/1.jpg", "/images/products/msi-05/2.jpg", "/images/products/msi-05/3.jpg"],
    warranty: "2 years official MSI warranty",
    description: "World-class creator workstation with 4K UHD+ OLED display, Intel Core Ultra 9, NVIDIA Studio RTX 4060, and 99.9Wh max legal battery.",
    specs: {
      processor: "Intel Core Ultra 9 185H",
      ram: "32GB LPDDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4060 8GB Studio",
      screenSize: "16.0\"",
      resolution: "4K UHD+ (3840 x 2400)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Home",
      battery: "99.9Wh \u2014 up to 14 hours",
      weight: "1.60 kg",
      warranty: "2 years official MSI warranty",
      usage: "Creator",
      screen: "16.0\" 4K UHD+ OLED 100% DCI-P3 DisplayHDR 600",
    },
    sold: 45,
    active: true,
    createdAt: "2026-08-05",
  },
  {
    id: "msi-06",
    name: "MSI Commercial 14 H A13MG",
    brand: "MSI",
    category: "Business Laptop",
    price: 13999000,
    oldPrice: 14999000,
    rating: 4.8,
    reviews: 52,
    stock: 9,
    badges: ["Smart Card Reader", "Windows 11 Pro"],
    image: "/images/products/msi-06/1.jpg",
    gallery: ["/images/products/msi-06/1.jpg", "/images/products/msi-06/2.jpg"],
    warranty: "3 years official MSI Commercial warranty",
    description: "High-security business laptop featuring integrated Smart Card Reader, NFC, Intel Core i7-13700H, and enterprise Windows 11 Pro.",
    specs: {
      processor: "Intel Core i7-13700H",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "Intel Iris Xe Graphics",
      screenSize: "14.0\"",
      resolution: "FHD+ (1920 x 1200)",
      refreshRate: "60Hz",
      operatingSystem: "Windows 11 Pro",
      battery: "53.8Wh \u2014 up to 9 hours",
      weight: "1.60 kg",
      warranty: "3 years official MSI Commercial warranty",
      usage: "Business",
      screen: "14.0\" FHD+ 16:10 IPS (Smart Card Reader)",
    },
    sold: 68,
    active: true,
    createdAt: "2026-08-06",
  },
  {
    id: "msi-07",
    name: "MSI Thin 15 B12UC",
    brand: "MSI",
    category: "Gaming Laptop",
    price: 10499000,
    oldPrice: 11299000,
    rating: 4.7,
    reviews: 170,
    stock: 12,
    badges: ["Ultra Thin 1.86kg", "144Hz Gaming"],
    image: "/images/products/msi-07/1.png",
    gallery: ["/images/products/msi-07/1.png", "/images/products/msi-07/2.jpg"],
    warranty: "2 years official MSI warranty",
    description: "Slim and lightweight budget gaming laptop weighing just 1.86kg with RTX 3050, 144Hz display, and Cooler Boost cooling technology.",
    specs: {
      processor: "Intel Core i5-12450H",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 3050 4GB",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "144Hz",
      operatingSystem: "Windows 11 Home",
      battery: "52.4Wh \u2014 up to 6 hours",
      weight: "1.86 kg",
      warranty: "2 years official MSI warranty",
      usage: "Gaming",
      screen: "15.6\" FHD 144Hz IPS-Level",
    },
    sold: 280,
    active: true,
    createdAt: "2026-08-07",
  },
  {
    id: "msi-08",
    name: "MSI Cyborg 15 A13VF",
    brand: "MSI",
    category: "Gaming Laptop",
    price: 15999000,
    oldPrice: 16999000,
    rating: 4.8,
    reviews: 115,
    stock: 9,
    badges: ["Cyberpunk Aesthetic", "RTX 4060"],
    image: "/images/products/msi-08/1.png",
    gallery: ["/images/products/msi-08/1.png", "/images/products/msi-08/2.jpg"],
    warranty: "2 years official MSI warranty",
    description: "Futuristic cyberpunk-styled gaming laptop with translucent chassis parts, Intel Core i7-13620H, and NVIDIA GeForce RTX 4060 graphics.",
    specs: {
      processor: "Intel Core i7-13620H",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      screenSize: "15.6\"",
      resolution: "FHD (1920 x 1080)",
      refreshRate: "144Hz",
      operatingSystem: "Windows 11 Home",
      battery: "53.5Wh \u2014 up to 7 hours",
      weight: "1.98 kg",
      warranty: "2 years official MSI warranty",
      usage: "Gaming",
      screen: "15.6\" FHD 144Hz (Translucent Cyberpunk)",
    },
    sold: 165,
    active: true,
    createdAt: "2026-08-08",
  },
  {
    id: "msi-09",
    name: "MSI Katana 15 B13VGK",
    brand: "MSI",
    category: "Gaming Laptop",
    price: 21999000,
    oldPrice: 23499000,
    rating: 4.9,
    reviews: 95,
    stock: 6,
    badges: ["RTX 4070", "Cooler Boost 5"],
    image: "/images/products/msi-09/1.png",
    gallery: ["/images/products/msi-09/1.png", "/images/products/msi-09/2.png", "/images/products/msi-09/3.jpg"],
    warranty: "2 years official MSI warranty",
    description: "Sharpened gaming performance with NVIDIA GeForce RTX 4070, Cooler Boost 5 dual fans with 6 heat pipes, and 165Hz QHD gaming screen.",
    specs: {
      processor: "Intel Core i7-13620H",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4070 8GB",
      screenSize: "15.6\"",
      resolution: "QHD (2560 x 1440)",
      refreshRate: "165Hz",
      operatingSystem: "Windows 11 Home",
      battery: "53.5Wh \u2014 up to 6 hours",
      weight: "2.25 kg",
      warranty: "2 years official MSI warranty",
      usage: "Gaming",
      screen: "15.6\" QHD 165Hz 100% DCI-P3 (Cooler Boost 5)",
    },
    sold: 110,
    active: true,
    createdAt: "2026-08-09",
  },
  {
    id: "msi-10",
    name: "MSI Stealth 16 AI Studio A1VGG",
    brand: "MSI",
    category: "Creator & Design",
    price: 34999000,
    oldPrice: 36999000,
    rating: 4.9,
    reviews: 55,
    stock: 4,
    badges: ["Ultra Thin 1.99kg", "QHD+ 240Hz"],
    image: "/images/products/msi-10/1.jpg",
    gallery: ["/images/products/msi-10/1.jpg", "/images/products/msi-10/2.jpg"],
    warranty: "2 years official MSI warranty",
    description: "Magnesium-aluminum alloy dual-purpose gaming and creator ultrabook with Intel Core Ultra 9, RTX 4070, 2TB SSD, and 240Hz QHD+ display.",
    specs: {
      processor: "Intel Core Ultra 9 185H",
      ram: "32GB DDR5",
      storage: "2TB NVMe SSD",
      gpu: "NVIDIA GeForce RTX 4070 8GB",
      screenSize: "16.0\"",
      resolution: "QHD+ (2560 x 1600)",
      refreshRate: "240Hz",
      operatingSystem: "Windows 11 Home",
      battery: "99.9Wh \u2014 up to 9 hours",
      weight: "1.99 kg",
      warranty: "2 years official MSI warranty",
      usage: "Creator",
      screen: "16.0\" QHD+ 240Hz 100% DCI-P3 OLED",
    },
    sold: 48,
    active: true,
    createdAt: "2026-08-10",
  },
  {
    id: "apple-01",
    name: "Apple MacBook Air 13 M2 (2024 Base)",
    brand: "Apple",
    category: "Student Laptop",
    price: 12999000,
    oldPrice: 13999000,
    rating: 4.9,
    reviews: 310,
    stock: 16,
    badges: ["Best Seller", "18 Jam Baterai"],
    image: "/images/products/apple-01/1.png",
    gallery: ["/images/products/apple-01/1.png", "/images/products/apple-01/2.jpg", "/images/products/apple-01/3.jpg"],
    warranty: "1 year official Apple warranty",
    description: "Ultra-portable fanless design with Apple M2 chip (8-Core CPU / 8-Core GPU), Liquid Retina display, MagSafe 3 charging, and 18 hours of battery life.",
    specs: {
      processor: "Apple M2 (8-core CPU)",
      ram: "8GB Unified Memory",
      storage: "256GB SSD",
      gpu: "Apple 8-core GPU",
      screenSize: "13.6\"",
      resolution: "Liquid Retina (2560 x 1664)",
      refreshRate: "60Hz",
      operatingSystem: "macOS Sequoia",
      battery: "52.6Wh \u2014 up to 18 hours",
      weight: "1.24 kg",
      warranty: "1 year official Apple warranty",
      usage: "Student",
      screen: "13.6\" Liquid Retina 500nits True Tone",
    },
    sold: 450,
    active: true,
    createdAt: "2026-08-01",
  },
  {
    id: "apple-02",
    name: "Apple MacBook Air 13 M2 (16GB RAM)",
    brand: "Apple",
    category: "Student Laptop",
    price: 15499000,
    oldPrice: 16499000,
    rating: 4.9,
    reviews: 195,
    stock: 12,
    badges: ["16GB RAM", "10-Core GPU"],
    image: "/images/products/apple-02/1.jpg",
    gallery: ["/images/products/apple-02/1.jpg", "/images/products/apple-02/2.png"],
    warranty: "1 year official Apple warranty",
    description: "Upgraded MacBook Air with 16GB Unified Memory, 10-core GPU, 512GB SSD, 1080p FaceTime HD camera, and whisper-quiet fanless operation.",
    specs: {
      processor: "Apple M2 (8-core CPU)",
      ram: "16GB Unified Memory",
      storage: "512GB SSD",
      gpu: "Apple 10-core GPU",
      screenSize: "13.6\"",
      resolution: "Liquid Retina (2560 x 1664)",
      refreshRate: "60Hz",
      operatingSystem: "macOS Sequoia",
      battery: "52.6Wh \u2014 up to 18 hours",
      weight: "1.24 kg",
      warranty: "1 year official Apple warranty",
      usage: "Student",
      screen: "13.6\" Liquid Retina 500nits True Tone",
    },
    sold: 280,
    active: true,
    createdAt: "2026-08-02",
  },
  {
    id: "apple-03",
    name: "Apple MacBook Air 13 M3 (8-Core CPU)",
    brand: "Apple",
    category: "Coding & Programming",
    price: 17999000,
    oldPrice: 18999000,
    rating: 4.9,
    reviews: 210,
    stock: 10,
    badges: ["Hardware Ray Tracing", "Dual Display"],
    image: "/images/products/apple-03/1.jpg",
    gallery: ["/images/products/apple-03/1.jpg", "/images/products/apple-03/2.jpg"],
    warranty: "1 year official Apple warranty",
    description: "Supercharged by Apple M3 chip with hardware-accelerated ray tracing, support for up to two external displays, and blazing fast Wi-Fi 6E.",
    specs: {
      processor: "Apple M3 (8-core CPU)",
      ram: "16GB Unified Memory",
      storage: "512GB SSD",
      gpu: "Apple 10-core GPU",
      screenSize: "13.6\"",
      resolution: "Liquid Retina (2560 x 1664)",
      refreshRate: "60Hz",
      operatingSystem: "macOS Sequoia",
      battery: "52.6Wh \u2014 up to 18 hours",
      weight: "1.24 kg",
      warranty: "1 year official Apple warranty",
      usage: "Coding",
      screen: "13.6\" Liquid Retina 500nits P3 (Ray Tracing)",
    },
    sold: 310,
    active: true,
    createdAt: "2026-08-03",
  },
  {
    id: "apple-04",
    name: "Apple MacBook Air 15 M3 (10-Core GPU)",
    brand: "Apple",
    category: "Creator & Design",
    price: 21499000,
    oldPrice: 22999000,
    rating: 4.9,
    reviews: 165,
    stock: 8,
    badges: ["15.3\" Big Screen", "Six-Speaker Sound"],
    image: "/images/products/apple-04/1.jpg",
    gallery: ["/images/products/apple-04/1.jpg", "/images/products/apple-04/2.jpg", "/images/products/apple-04/3.jpg"],
    warranty: "1 year official Apple warranty",
    description: "Expansive 15.3-inch Liquid Retina display in an impossibly thin 11.5mm chassis, with Apple M3 chip and six-speaker sound system with Spatial Audio.",
    specs: {
      processor: "Apple M3 (8-core CPU)",
      ram: "16GB Unified Memory",
      storage: "512GB SSD",
      gpu: "Apple 10-core GPU",
      screenSize: "15.3\"",
      resolution: "Liquid Retina (2880 x 1864)",
      refreshRate: "60Hz",
      operatingSystem: "macOS Sequoia",
      battery: "66.5Wh \u2014 up to 18 hours",
      weight: "1.51 kg",
      warranty: "1 year official Apple warranty",
      usage: "Creator",
      screen: "15.3\" Liquid Retina 500nits P3",
    },
    sold: 220,
    active: true,
    createdAt: "2026-08-04",
  },
  {
    id: "apple-05",
    name: "Apple MacBook Air 13 M4 (2026 Edition)",
    brand: "Apple",
    category: "Student Laptop",
    price: 19499000,
    oldPrice: 20999000,
    rating: 4.9,
    reviews: 130,
    stock: 9,
    badges: ["Apple Intelligence", "Next-Gen M4"],
    image: "/images/products/apple-05/1.jpg",
    gallery: ["/images/products/apple-05/1.jpg", "/images/products/apple-05/2.jpg"],
    warranty: "1 year official Apple warranty",
    description: "Next-generation MacBook Air with 10-core Apple M4 chip, built for personal AI with Apple Intelligence, 16GB unified memory standard, and all-day battery.",
    specs: {
      processor: "Apple M4 (10-core CPU)",
      ram: "16GB Unified Memory",
      storage: "512GB SSD",
      gpu: "Apple 10-core GPU",
      screenSize: "13.6\"",
      resolution: "Liquid Retina (2560 x 1664)",
      refreshRate: "60Hz",
      operatingSystem: "macOS Sequoia",
      battery: "52.6Wh \u2014 up to 18 hours",
      weight: "1.24 kg",
      warranty: "1 year official Apple warranty",
      usage: "Student",
      screen: "13.6\" Liquid Retina (Apple Intelligence)",
    },
    sold: 190,
    active: true,
    createdAt: "2026-08-05",
  },
  {
    id: "apple-06",
    name: "Apple MacBook Air 15 M4 (24GB RAM)",
    brand: "Apple",
    category: "Business Laptop",
    price: 25999000,
    oldPrice: 27499000,
    rating: 4.9,
    reviews: 85,
    stock: 6,
    badges: ["24GB Unified", "1TB SSD"],
    image: "/images/products/apple-06/1.jpg",
    gallery: ["/images/products/apple-06/1.jpg", "/images/products/apple-06/2.jpg"],
    warranty: "1 year official Apple warranty",
    description: "Executive grade 15.3-inch MacBook Air configured with 24GB unified memory, 1TB high-speed SSD, and powerful 10-core Apple M4 processor.",
    specs: {
      processor: "Apple M4 (10-core CPU)",
      ram: "24GB Unified Memory",
      storage: "1TB SSD",
      gpu: "Apple 10-core GPU",
      screenSize: "15.3\"",
      resolution: "Liquid Retina (2880 x 1864)",
      refreshRate: "60Hz",
      operatingSystem: "macOS Sequoia",
      battery: "66.5Wh \u2014 up to 18 hours",
      weight: "1.51 kg",
      warranty: "1 year official Apple warranty",
      usage: "Business",
      screen: "15.3\" Liquid Retina 500nits True Tone",
    },
    sold: 110,
    active: true,
    createdAt: "2026-08-06",
  },
  {
    id: "apple-07",
    name: "Apple MacBook Pro 14 M3 (Standard)",
    brand: "Apple",
    category: "Coding & Programming",
    price: 24999000,
    oldPrice: 26999000,
    rating: 4.9,
    reviews: 140,
    stock: 7,
    badges: ["XDR 120Hz", "Pro Display"],
    image: "/images/products/apple-07/1.png",
    gallery: ["/images/products/apple-07/1.png", "/images/products/apple-07/2.png", "/images/products/apple-07/3.png"],
    warranty: "1 year official Apple warranty",
    description: "Pro-level performance with Apple M3 chip, Liquid Retina XDR display with 120Hz ProMotion (1600 nits peak HDR), HDMI port, and SDXC card reader.",
    specs: {
      processor: "Apple M3 (8-core CPU)",
      ram: "16GB Unified Memory",
      storage: "512GB SSD",
      gpu: "Apple 10-core GPU",
      screenSize: "14.2\"",
      resolution: "Liquid Retina XDR (3024 x 1964)",
      refreshRate: "120Hz",
      operatingSystem: "macOS Sequoia",
      battery: "70Wh \u2014 up to 22 hours",
      weight: "1.55 kg",
      warranty: "1 year official Apple warranty",
      usage: "Coding",
      screen: "14.2\" Liquid Retina XDR 120Hz ProMotion",
    },
    sold: 175,
    active: true,
    createdAt: "2026-08-07",
  },
  {
    id: "apple-08",
    name: "Apple MacBook Pro 14 M4 (10-Core CPU)",
    brand: "Apple",
    category: "Coding & Programming",
    price: 27999000,
    oldPrice: 29999000,
    rating: 5.0,
    reviews: 110,
    stock: 7,
    badges: ["24 Jam Baterai", "Apple Intelligence"],
    image: "/images/products/apple-08/1.jpg",
    gallery: ["/images/products/apple-08/1.jpg", "/images/products/apple-08/2.jpg", "/images/products/apple-08/3.jpg"],
    warranty: "1 year official Apple warranty",
    description: "Next-gen pro laptop featuring 10-core Apple M4 chip with 1TB SSD, 1000 nits SDR brightness, nano-texture glass option, and record 24-hour battery life.",
    specs: {
      processor: "Apple M4 (10-core CPU)",
      ram: "16GB Unified Memory",
      storage: "1TB SSD",
      gpu: "Apple 10-core GPU",
      screenSize: "14.2\"",
      resolution: "Liquid Retina XDR (3024 x 1964)",
      refreshRate: "120Hz",
      operatingSystem: "macOS Sequoia",
      battery: "72.4Wh \u2014 up to 24 hours",
      weight: "1.55 kg",
      warranty: "1 year official Apple warranty",
      usage: "Coding",
      screen: "14.2\" Liquid Retina XDR 120Hz 1000nits SDR",
    },
    sold: 140,
    active: true,
    createdAt: "2026-08-08",
  },
  {
    id: "apple-09",
    name: "Apple MacBook Pro 14 M4 Pro (12-Core)",
    brand: "Apple",
    category: "Coding & Programming",
    price: 33999000,
    oldPrice: 35999000,
    rating: 5.0,
    reviews: 85,
    stock: 5,
    badges: ["Thunderbolt 5", "M4 Pro"],
    image: "/images/products/apple-09/1.png",
    gallery: ["/images/products/apple-09/1.png", "/images/products/apple-09/2.png"],
    warranty: "1 year official Apple warranty",
    description: "Insane developer and studio performance with Apple M4 Pro (12-core CPU / 16-core GPU), 24GB unified memory, and Thunderbolt 5 with 120Gb/s speeds.",
    specs: {
      processor: "Apple M4 Pro (12-core CPU)",
      ram: "24GB Unified Memory",
      storage: "1TB SSD",
      gpu: "Apple 16-core GPU",
      screenSize: "14.2\"",
      resolution: "Liquid Retina XDR (3024 x 1964)",
      refreshRate: "120Hz",
      operatingSystem: "macOS Sequoia",
      battery: "72.4Wh \u2014 up to 22 hours",
      weight: "1.60 kg",
      warranty: "1 year official Apple warranty",
      usage: "Coding",
      screen: "14.2\" Liquid Retina XDR 120Hz (Thunderbolt 5)",
    },
    sold: 95,
    active: true,
    createdAt: "2026-08-09",
  },
  {
    id: "apple-10",
    name: "Apple MacBook Pro 16 M4 Pro (14-Core)",
    brand: "Apple",
    category: "Creator & Design",
    price: 35999000,
    oldPrice: 38999000,
    rating: 5.0,
    reviews: 75,
    stock: 4,
    badges: ["Flagship 16.2\"", "36GB Unified"],
    image: "/images/products/apple-10/1.png",
    gallery: ["/images/products/apple-10/1.png", "/images/products/apple-10/2.jpg", "/images/products/apple-10/3.png"],
    warranty: "1 year official Apple warranty",
    description: "Massive 16.2-inch Liquid Retina XDR workstation with Apple M4 Pro (14-core CPU / 20-core GPU), 36GB unified memory, and 24 hours of battery life.",
    specs: {
      processor: "Apple M4 Pro (14-core CPU)",
      ram: "36GB Unified Memory",
      storage: "1TB SSD",
      gpu: "Apple 20-core GPU",
      screenSize: "16.2\"",
      resolution: "Liquid Retina XDR (3456 x 2234)",
      refreshRate: "120Hz",
      operatingSystem: "macOS Sequoia",
      battery: "100Wh \u2014 up to 24 hours",
      weight: "2.14 kg",
      warranty: "1 year official Apple warranty",
      usage: "Creator",
      screen: "16.2\" Liquid Retina XDR 120Hz ProMotion",
    },
    sold: 80,
    active: true,
    createdAt: "2026-08-10",
  },
];

export const seedOrders: Order[] = [
  {
    id: "LAP-10241",
    customer: "Almira Putri",
    email: "almira@example.com",
    date: "2026-08-27",
    total: 33999000,
    status: "Shipped",
    payment: "Bank Transfer",
    items: [{ name: "Apple MacBook Pro 14 M4 Pro (12-Core)", qty: 1, price: 33999000 }],
  },
  {
    id: "LAP-10240",
    customer: "Rendi Saputra",
    email: "rendi@example.com",
    date: "2026-08-26",
    total: 22499000,
    status: "Processing",
    payment: "QRIS",
    items: [{ name: "Lenovo Legion 5i 16IRX9", qty: 1, price: 22499000 }],
  },
  {
    id: "LAP-10239",
    customer: "Dewi Anggraini",
    email: "dewi@example.com",
    date: "2026-08-24",
    total: 19499000,
    status: "Completed",
    payment: "QRIS",
    items: [{ name: "Apple MacBook Air 13 M4 (2026 Edition)", qty: 1, price: 19499000 }],
  },
  {
    id: "LAP-10238",
    customer: "Bagus Wirawan",
    email: "bagus@example.com",
    date: "2026-08-22",
    total: 12999000,
    status: "Pending",
    payment: "COD",
    items: [{ name: "Lenovo LOQ 15IAX9", qty: 1, price: 12999000 }],
  },
  {
    id: "LAP-10237",
    customer: "Sinta Larasati",
    email: "sinta@example.com",
    date: "2026-08-20",
    total: 5499000,
    status: "Cancelled",
    payment: "Bank Transfer",
    items: [{ name: "ASUS Vivobook Go 14 E1404FA", qty: 1, price: 5499000 }],
  },
];

export const orderStatuses: OrderStatus[] = [
  "Pending",
  "Processing",
  "Shipped",
  "Completed",
  "Cancelled",
];
